name: mined
description: My project.

publish_to: 'none'

version: 2.6.0+31

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.5.0
  dio: ^5.3.3
  provider: ^6.0.5
  shared_preferences: ^2.2.1
  permission_handler: ^11.0.0
  google_sign_in: ^6.1.5
  flutter_facebook_auth: ^6.0.2
  carousel_slider: ^4.2.1
  chips_choice: ^3.0.1
  grouped_list: ^5.1.2
  intl: ^0.19.0
  easy_localization: ^3.0.3
  azlistview: ^2.0.0
  firebase_core: ^2.17.0
  firebase_messaging: ^14.6.9
  flutter_local_notifications: ^17.0.0
  sign_in_with_apple: ^5.0.0
  package_info_plus: ^5.0.1
  url_launcher: ^6.1.14
  animated_splash_screen: ^1.3.0
  version: ^3.0.2
  app_settings: ^5.1.1
  syncfusion_flutter_charts: ^25.1.35
  flutter_widget_from_html: ^0.14.6
  flutter_dotenv: ^5.1.0
  flutter_speed_dial: ^7.0.0
  flutter_tts: ^4.0.1
  pinput: ^4.0.0
  camera: ^0.11.0
  google_mlkit_face_detection: ^0.9.0
  image_picker: ^1.0.7
  device_info_plus: ^9.1.2
  ed_screen_recorder: ^0.0.14
  path_provider: ^2.1.3
  screen_recorder: ^0.2.0
  ffmpeg_kit_flutter: ^6.0.3
  video_player: ^2.8.6
  audioplayers: ^5.2.1
  just_audio: ^0.9.38
  http_parser: ^4.0.2
  camera_android: ^0.10.9+2
  wakelock_plus: ^1.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/
    - assets/sound/
    - prod.env
    - dev.env
